name: Publish Package
on:
  release:
    types: [created]
  workflow_dispatch:
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v6
      with:
        node-version: '24.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    # Build
    - run: npm run build
    # Publish to npm
    - run: npm publish --access public
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v6
      with:
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@revolist'
    # Publish to GitHub Packages
    - run: npm publish
